name: gallery_vault
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  gallery_saver: ^2.3.2
  shared_preferences: ^2.2.1
  get: ^4.6.5
  get_storage: ^2.1.1
  loading_animation_widget: ^1.2.0+4
  bot_toast: ^4.0.3
  share_plus: ^6.3.0
  webview_flutter: 4.2.2
  lottie: ^2.6.0
  flutter_overlay_loader: ^2.0.0
  url_launcher: ^6.1.11
  onesignal_flutter:
  loading_indicator: ^3.1.1
  flutter_jailbreak_detection: ^1.10.0
  flutter_secure_storage: ^5.0.3
  app_settings: ^5.0.0
#  google_mobile_ads: ^3.0.0
#  facebook_audience_network: ^1.0.1
#  applovin_max: ^3.0.1
#  ads_sdk:
#    path: ./ads_sdk
  flutter_lints: ^2.0.0
  card_swiper: ^2.0.4
  chewie: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  photo_manager: ^2.7.1
  provider: ^6.0.5
  video_player: ^2.5.2
  image_editor_plus:
  permission_handler:
  device_info_plus: ^8.1.0
  intl:
  photo_view: ^0.14.0
  flutter_wallpaper_manager: ^0.0.4
  open_file: ^3.3.2
  connectivity_plus:
  privacy_screen: ^0.0.6
  flutter_easyloading: ^3.0.5
  draggable_scrollbar: ^0.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  file_picker:
  image_cropper: 4.0.1
  saf: ^1.0.3+4
  fluttertoast: ^8.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
     - asset/images/
     - asset/json/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: MuseoModerno
       fonts:
         - asset: asset/font/MuseoModerno-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
     - family: Urbanist
       fonts:
         - asset: asset/font/Urbanist-Regular.ttf
##         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
